/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerRole = IDL.Variant({
  'bowler' : IDL.Null,
  'allrounder' : IDL.Null,
  'wicketkeeper' : IDL.Null,
  'batsman' : IDL.Null,
});
export const Player = IDL.Record({
  'credits' : IDL.Int,
  'name' : IDL.Text,
  'role' : PlayerRole,
  'team' : IDL.Text,
  'points' : IDL.Int,
});
export const Contest = IDL.Record({
  'participants' : IDL.Vec(IDL.Principal),
  'matchId' : IDL.Nat,
  'entryFee' : IDL.Int,
  'prizePool' : IDL.Int,
});
export const LeaderboardEntry = IDL.Record({
  'user' : IDL.Principal,
  'prize' : IDL.Int,
  'points' : IDL.Int,
});
export const MatchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'team1' : IDL.Text,
  'team2' : IDL.Text,
  'dateTime' : IDL.Text,
});

export const idlService = IDL.Service({
  'createTeam' : IDL.Func([IDL.Vec(Player), Player, Player], [], []),
  'getContestDetails' : IDL.Func([IDL.Nat], [IDL.Opt(Contest)], ['query']),
  'getContests' : IDL.Func([IDL.Nat], [IDL.Vec(Contest)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getParticipantsCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerRole = IDL.Variant({
    'bowler' : IDL.Null,
    'allrounder' : IDL.Null,
    'wicketkeeper' : IDL.Null,
    'batsman' : IDL.Null,
  });
  const Player = IDL.Record({
    'credits' : IDL.Int,
    'name' : IDL.Text,
    'role' : PlayerRole,
    'team' : IDL.Text,
    'points' : IDL.Int,
  });
  const Contest = IDL.Record({
    'participants' : IDL.Vec(IDL.Principal),
    'matchId' : IDL.Nat,
    'entryFee' : IDL.Int,
    'prizePool' : IDL.Int,
  });
  const LeaderboardEntry = IDL.Record({
    'user' : IDL.Principal,
    'prize' : IDL.Int,
    'points' : IDL.Int,
  });
  const MatchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'team1' : IDL.Text,
    'team2' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  
  return IDL.Service({
    'createTeam' : IDL.Func([IDL.Vec(Player), Player, Player], [], []),
    'getContestDetails' : IDL.Func([IDL.Nat], [IDL.Opt(Contest)], ['query']),
    'getContests' : IDL.Func([IDL.Nat], [IDL.Vec(Contest)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getParticipantsCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };