/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contest {
  'participants' : Array<Principal>,
  'matchId' : bigint,
  'entryFee' : bigint,
  'prizePool' : bigint,
}
export interface LeaderboardEntry {
  'user' : Principal,
  'prize' : bigint,
  'points' : bigint,
}
export interface Match {
  'id' : bigint,
  'status' : MatchStatus,
  'team1' : string,
  'team2' : string,
  'dateTime' : string,
}
export type MatchStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export interface Player {
  'credits' : bigint,
  'name' : string,
  'role' : PlayerRole,
  'team' : string,
  'points' : bigint,
}
export type PlayerRole = { 'bowler' : null } |
  { 'allrounder' : null } |
  { 'wicketkeeper' : null } |
  { 'batsman' : null };
export interface _SERVICE {
  'createTeam' : ActorMethod<[Array<Player>, Player, Player], undefined>,
  'getContestDetails' : ActorMethod<[bigint], [] | [Contest]>,
  'getContests' : ActorMethod<[bigint], Array<Contest>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMatches' : ActorMethod<[], Array<Match>>,
  'getParticipantsCount' : ActorMethod<[bigint], bigint>,
  'getPlayers' : ActorMethod<[], Array<Player>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];