/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    credits: bigint;
    name: string;
    role: PlayerRole;
    team: string;
    points: bigint;
}
export interface LeaderboardEntry {
    user: Principal;
    prize: bigint;
    points: bigint;
}
export interface Match {
    id: bigint;
    status: MatchStatus;
    team1: string;
    team2: string;
    dateTime: string;
}
export interface Contest {
    participants: Array<Principal>;
    matchId: bigint;
    entryFee: bigint;
    prizePool: bigint;
}
export enum MatchStatus {
    upcoming = "upcoming",
    live = "live",
    completed = "completed"
}
export enum PlayerRole {
    bowler = "bowler",
    allrounder = "allrounder",
    wicketkeeper = "wicketkeeper",
    batsman = "batsman"
}
export interface backendInterface {
    createTeam(players: Array<Player>, captain: Player, viceCaptain: Player): Promise<void>;
    getContestDetails(contestId: bigint): Promise<Contest | null>;
    getContests(matchId: bigint): Promise<Array<Contest>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMatches(): Promise<Array<Match>>;
    getParticipantsCount(contestId: bigint): Promise<bigint>;
    getPlayers(): Promise<Array<Player>>;
}
import type { Contest as _Contest, Match as _Match, MatchStatus as _MatchStatus, Player as _Player, PlayerRole as _PlayerRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createTeam(arg0: Array<Player>, arg1: Player, arg2: Player): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Player_n2(this._uploadFile, this._downloadFile, arg1), to_candid_Player_n2(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Player_n2(this._uploadFile, this._downloadFile, arg1), to_candid_Player_n2(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getContestDetails(arg0: bigint): Promise<Contest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContestDetails(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContestDetails(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContests(arg0: bigint): Promise<Array<Contest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContests(arg0);
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParticipantsCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getParticipantsCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParticipantsCount(arg0);
            return result;
        }
    }
    async getPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_MatchStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerRole): PlayerRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contest]): Contest | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credits: bigint;
    name: string;
    role: _PlayerRole;
    team: string;
    points: bigint;
}): {
    credits: bigint;
    name: string;
    role: PlayerRole;
    team: string;
    points: bigint;
} {
    return {
        credits: value.credits,
        name: value.name,
        role: from_candid_PlayerRole_n15(_uploadFile, _downloadFile, value.role),
        team: value.team,
        points: value.points
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MatchStatus;
    team1: string;
    team2: string;
    dateTime: string;
}): {
    id: bigint;
    status: MatchStatus;
    team1: string;
    team2: string;
    dateTime: string;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n10(_uploadFile, _downloadFile, value.status),
        team1: value.team1,
        team2: value.team2,
        dateTime: value.dateTime
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    live: null;
} | {
    completed: null;
}): MatchStatus {
    return "upcoming" in value ? MatchStatus.upcoming : "live" in value ? MatchStatus.live : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bowler: null;
} | {
    allrounder: null;
} | {
    wicketkeeper: null;
} | {
    batsman: null;
}): PlayerRole {
    return "bowler" in value ? PlayerRole.bowler : "allrounder" in value ? PlayerRole.allrounder : "wicketkeeper" in value ? PlayerRole.wicketkeeper : "batsman" in value ? PlayerRole.batsman : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n8(_uploadFile, _downloadFile, x));
}
function to_candid_PlayerRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): _PlayerRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Player_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Player): _Player {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credits: bigint;
    name: string;
    role: PlayerRole;
    team: string;
    points: bigint;
}): {
    credits: bigint;
    name: string;
    role: _PlayerRole;
    team: string;
    points: bigint;
} {
    return {
        credits: value.credits,
        name: value.name,
        role: to_candid_PlayerRole_n4(_uploadFile, _downloadFile, value.role),
        team: value.team,
        points: value.points
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): {
    bowler: null;
} | {
    allrounder: null;
} | {
    wicketkeeper: null;
} | {
    batsman: null;
} {
    return value == PlayerRole.bowler ? {
        bowler: null
    } : value == PlayerRole.allrounder ? {
        allrounder: null
    } : value == PlayerRole.wicketkeeper ? {
        wicketkeeper: null
    } : value == PlayerRole.batsman ? {
        batsman: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Player>): Array<_Player> {
    return value.map((x)=>to_candid_Player_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
